name: Benchmark
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'test/**'
    branches:
      - master
  workflow_dispatch:
jobs:
  bench:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1'
          job-summary: 'true'
          script: benchmark/benchmarks.jl
